spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:9010
  cloud:
    config:
      fail-fast: true


backend:
  service:
    url: http://localhost:8082/dummy-client2/saludo
  eureka:
    url: http://client2/dummy-client2/saludo